#138F submission page
openmsupply/application-manager-server pull request #163
Opened 2021-01-01 07:33 UTC by nmadruga

Branch to be used in pair with Front PR of [issue#138](https://github.com/openmsupply/application-manager-web-app/issues/138)

## Changes
- Add `submissionMessage` to some template. The ones without a submission message will get the default one.
- Add `description` to stages on each existing template.

2021-01-04 23:46 UTC, CarlosNZ commented
Should the base branch be #182F?

2021-01-06 01:18 UTC, CarlosNZ requested changes
Just typos. :)

2021-01-06 01:18 UTC, CarlosNZ commented on database/insertData.js
> +                description: "This application will go trhought the screening stage before can be accessed."
```suggestion
                description: "This application will go through the Screening stage before it can be accessed."
```

2021-01-07 04:02 UTC, nmadruga commented
Changes are done. Thanks!

2021-01-07 04:04 UTC, CarlosNZ approved these changes
👍

2021-01-07 04:12 UTC, merged