#214 Refactor db connect methods to individual plugin methods
openmsupply/application-manager-server pull request #222
Opened 2021-02-17 12:14 UTC by sworup

2021-02-17 21:26 UTC, andreievg commented
@CarlosNZ, would you mind looking at this please ?

2021-02-17 21:27 UTC, CarlosNZ requested changes
Great, thanks for making a start on these. I've made a couple of small comments in the code.

Also:

- Can you merge the latest `master` into this? I'd like to check that all the tests work before approving, and there's some that are failing now and were only fixed in a later PR to the one you've branched off
- We seem to be having a problem with the compiled .js files on plugins that have multiple .js files in them (See issue #221). For now, can you leave out the .js files on any of the plugins you've worked on (just delete them) until we figure out what's going on there

2021-02-23 08:26 UTC, sworup commented on src/plugins/types.ts
> +
Resolved with 8c17f42

2021-02-24 21:27 UTC, CarlosNZ commented
Thanks @sworup, can you just delete the extra .js files, cos we're still getting the error I mentioned above? Thx

2021-04-13 03:09 UTC, andreievg commented
hmm, i think there are too many conflicts now, and we've decided to just relocate the methods when an action is touched. closing

2021-04-13 03:09 UTC, closed without merging