#384-2 lao templates update
openmsupply/application-manager-server pull request #403
Opened 2021-06-10 14:08 UTC by andreievg

Added some changes to get ready for demo server:

### Changes

* Tried to minimise and simplify permissions names and user set for lao data file
* Added further user outcomes
* Added further org outcomes
* Changed default values for object response to be an empty object
* Made populated fields editable (for licence)
* Fixed professional details in licence

2021-06-10 22:35 UTC, nmadruga requested changes
Great. Thanks for the final touches!

I realised I hadn't commit the outcomes for licenses yesterday before going home. Sorry about that. Now it's already on `master` so it should be easier for us to test other PR on top of existing templates.

My only concern with the changes here is that allowing the user to edit pre-filled fields would be misleading regarding - this fields aren't updated in the user/organisation table and if they are - users need to re-upload documents since they are making changes to what was reviewed/approved during the company registration process.

2021-06-10 22:35 UTC, nmadruga commented on database/insertData/laos/02_template_orgRegistration.js
> +                      isRequired: true # TO-DO make required for production
Can remove todo

2021-06-10 22:35 UTC, nmadruga commented on database/insertData/laos/02_template_orgRegistration.js
> +                      isRequired: true # TO-DO make required for production
In all next one too : )

2021-06-10 22:35 UTC, nmadruga commented on database/insertData/laos/03_template_license_MMC_MMD.js
> -                        isEditable: false
For all of the above. Isn't it misleading to allow the user to change this, but that doesn't update the record in the system? And if it does, I think the documents that prove need to be re-uploaded (this is regarding "Organisation category" basically)

2021-06-10 22:35 UTC, nmadruga commented on database/insertData/laos/03_template_license_MMC_MMD.js
> +                            validationMessage: "Not a valid email address"
Same thing about re-uploading documents on this one: 
- **LMMD02** – CV of applicant with recent (max 1 year) photo
- **LMMD06** – Certificate of education level
- **LMMD08** – Letter from previous employers documenting at least 3 years professional experience (for private sector must be certified by provincial or capital level)
- **LMMD09** – Documentation showing resignation from previous employment (for private sector must be certified by provincial or capital level)
- **LMMD09** – Documentation showing resignation from previous employment (for private sector must be certified by provincial or capital level)

2021-06-10 22:35 UTC, nmadruga commented on database/insertData/laos/03_template_license_MMC_MMD.js
>                            properties: [
Same thing about re-uploading documents (if we allow changing this fields from company/ownership):

### Owner
- **LMMD03** – Medical Certificate (max 3 months)
- **LMMD04** – Certificate of current residence with photo (max 3 months)
- **LMMD05** – Recent (max 1 year) photo
- **LMMD07** – Criminal record "number 3"

### Company
- **LMMD10** – Map of location of company
- **LMMD11** – Layout of facilities
- **LMMD13** – Proof of ownership of facilities or contract of rent
- **LMMD14** – Copy of business licence issued by Ministry of Commerce

2021-06-10 23:48 UTC, andreievg commented
> My only concern with the changes here is that allowing the user to edit pre-filled fields would be misleading regarding - this fields aren't updated in the user/organisation table and if they are - users need to re-upload documents since they are making changes to what was reviewed/approved during the company registration process.

Would this be ok (https://github.com/openmsupply/application-manager-web-app/pull/779#issuecomment-858516751, and subsequent comments)

2021-06-13 23:53 UTC, nmadruga commented
Sure. That's all good. Have this been implemented here already?

2021-06-14 00:25 UTC, nmadruga reviewed
Not sure where is the problem... But I'm now getting this problem when trying to run the `yarn database_init laos`:
![Screen Shot 2021-06-14 at 12 24 21 PM](https://user-images.githubusercontent.com/16461988/121826399-900c6d80-cd0b-11eb-9ea0-5e9bbd2edd73.png)

Will be waiting on the fix to test this again.

2021-06-14 22:13 UTC, CarlosNZ requested changes
Just a couple of tiny comments

2021-06-14 22:13 UTC, CarlosNZ commented on database/insertData/laos/02_template_orgRegistration.js
> +                      title: "Pofessional Id"
Spelling -- revert?

2021-06-14 22:13 UTC, CarlosNZ commented on database/insertData/laos/02_template_orgRegistration.js
> +                    { 1
There's the glitch that is causing the error!

2021-06-14 22:14 UTC, CarlosNZ commented
> Not sure where is the problem... But I'm now getting this problem when trying to run the `yarn database_init laos`:

There's the problem, if you want to fix it for testing: https://github.com/openmsupply/application-manager-server/pull/403#discussion_r651312752

2021-06-16 00:05 UTC, nmadruga commented
Great catch @CarlosNZ. I think I'll be fixing the spelling mistake and what you pointed out and will merge this one, since I want to merge my next PR in, and so we try to keep the list of PRs shorter. It gets to a point that is very hard to work like that.

Let me know if any problems to merge in this one @andreievg.

2021-06-16 00:07 UTC, CarlosNZ commented
> Great catch @CarlosNZ. I think I'll be fixing the spelling mistake and what you pointed out and will merge this one, since I want to merge my next PR in, and so we try to keep the list of PRs shorter. It gets to a point that is very hard to work like that.
> 
> Let me know if any problems to merge in this one @andreievg.

Yeah sounds good. Merge 👍🏼

2021-06-16 00:52 UTC, merged