Template builder
openmsupply/application-manager-server pull request #455
Opened 2021-07-14 10:03 UTC by andreievg

Required for front end branch in this PR:

* Template section to be unique code within a template
* Template version timestamp to be updated when inserted/duplicated
* Template version trigger is also running on update (so that if template code is change on a template to an existing code, it doesn't cause conflict in version)
* Add isAdmin to permission policy, for UI control of admin options
* Extend template element and template action to get parameters as string (so we can query for text existing in the parameters, for permission policy info)
* Application to have is_config field to differentiate applications created in template builder vs normal applications
* Helper to delete whole application (including related records)
* Expose pg_policies view, for permission name info
* Change how permission row policies are created and configured (will make a seperate issue and PR for this), moral of the story, it was too slow to have row policy for each templatePermission (especially when permission restrictions are 'nested' and rely on other tables), so made row policies per policy only.
* Transferred lao users and org config from demo branch
* Snapshots and import from json to work for template export, import and duplication

2021-07-14 22:00 UTC, CarlosNZ requested changes
Nice work! I don't pretend to understand everything that's going on, but it's an impressive achievement. You'll have to explain to us the changes you made to the permissions at some point.

Couple of very minor comments.

2021-07-27 04:26 UTC, andreievg commented on database/buildSchema/16_application.sql
> +    is_config bool DEFAULT FALSE,
c252d9e6ae57af4683d1e7fedbf46b2d221bcf7e

2021-07-27 04:26 UTC, andreievg commented on src/components/snapshots/takeSnapshot.ts
> +    if (options.shouldReInitilise) await getSchemaDiff(newSnapshotFolder)
c252d9e6ae57af4683d1e7fedbf46b2d221bcf7e

2021-07-27 04:26 UTC, andreievg commented on database/snapshotOptions/templateExport.json
> +  "excludeInsertScripts": []
work in progress

2021-08-02 00:57 UTC, CarlosNZ approved these changes

2021-08-02 02:29 UTC, merged