#553 Snapshots -- clear files option
openmsupply/application-manager-server pull request #554
Opened 2021-09-03 01:32 UTC by CarlosNZ

Fixes #533 

Added the option "resetFiles", and added it to existing "snapshotOptions" files:
- for full system snapshots ("default"), files folder is cleared on import
- for templates, individual templates, application data, files folder is NOT cleared on import

For existing snapshots (that don't have this parameter in their options file), they WON'T clear files (i.e. default: false)

We should add this option to current demo snapshot.

(Fixed a spelling error in "initialiseDatabase" function name as well)

2021-09-03 01:55 UTC, nmadruga commented
> Fixes #533

Fixes #553 ?

2021-09-03 01:58 UTC, CarlosNZ commented
> > Fixes #533
> 
> Fixes #553 ?

Yes 😳

2021-09-03 01:58 UTC, nmadruga commented
Good to have this added to some domentation on Snapshots? If we don't have one yet, can we start now?

2021-09-03 02:04 UTC, nmadruga requested changes
Testing:

- Have created a new snapshot and it good this option set by default: "resetFiles": **true** is that correct? Shouldn't it be **false**?

2021-09-03 02:07 UTC, CarlosNZ commented
> Have created a new snapshot and it good this option set by default: "resetFiles": **true** is that correct? Shouldn't it be **false**?

Yes, that is correct. Full snapshots (whole system) use the "default.json" options, and we want "resetFiles" to be true for those. It's "false" for all the others (templates etc).

2021-09-03 02:09 UTC, CarlosNZ commented
> Good to have this added to some documentation on Snapshots? If we don't have one yet, can we start now?

There is a "Snapshots.md" page, but it looks way out of date in terms of snapshot functionality so will need a substantial re-write. That'll be quite a big job, so I've made an issue for it: https://github.com/openmsupply/application-manager-server/issues/555

2021-09-05 21:30 UTC, nmadruga approved these changes

2021-09-05 22:02 UTC, merged