Fix setting assignedSections to null when status is AVAILABLE
openmsupply/application-manager-server pull request #660
Opened 2022-02-18 03:58 UTC by nmadruga

[Front-end PR](https://github.com/openmsupply/application-manager-web-app/pull/1124) in progress

2022-02-18 06:32 UTC, CarlosNZ reviewed
I think we should probably leave it as non-nullable, default `[]`. The only reason we were changing it is so we could mutate it from the front-end, but we're using the trigger instead so no need. If it's NULL we don't need the trigger, if we're using the trigger its easier to deal with as [] rather than null.

Non-nullables are so much less hassle to deal with in the front-end, don't you think?

2022-02-20 20:30 UTC, CarlosNZ commented
Also -- need to add migration code (can be part of 0.2.0 script, since we haven't released that yet)

2022-02-20 20:59 UTC, nmadruga commented
Yes, Carl. Thanks for inputs. I agree. Will be changing this after stand-up meeting : )

2022-02-20 23:30 UTC, CarlosNZ requested changes
Not sure how that incorrect field ended up in develop. Anyway, the trigger works once that's fixed.

2022-02-20 23:30 UTC, CarlosNZ commented on database/buildSchema/28_review_assignment.sql
> +-- TRIGGER (Listener) on review_assignment table: Set assignedSections to Null when changing status to AVAILABLE
```suggestion
-- TRIGGER (Listener) on review_assignment table: Set assignedSections to [] when changing status to AVAILABLE
```

2022-02-20 23:30 UTC, CarlosNZ commented on database/buildSchema/28_review_assignment.sql
>      AFTER UPDATE OF trigger ON public.review_assignment
```suggestion
    AFTER UPDATE OF status ON public.review_assignment
```

I thought we already fixed this? 🤔

2022-02-20 23:57 UTC, CarlosNZ approved these changes
Great thanks

2022-02-21 01:12 UTC, merged