#1109F Trigger/Function for deleting review question assignments
openmsupply/application-manager-server pull request #662
Opened 2022-02-21 11:08 UTC by CarlosNZ

Required for [front-end issue #1109](https://github.com/openmsupply/application-manager-web-app/issues/1109) (no PR yet)

The front-end had no knowledge of the state of existing review question assignments for items on the "Assignment" tab, so rather than write a bunch of additional front-end queries to fetch this info and then process it, it is simpler to leave the question_assignment handling to database triggers & functions.

There was a slight headache, in that the `delete_question_assignments` function's main query didn't work when "assigned_sections" was an empty array, so had to have slightly different logic for that case. Basically:
- trigger function runs when "assigned_sections" on "review_assignment" changes (either from the front-end, or reset via the existing review_assignment trigger)
- If sections remain assigned, this function deletes question assignments relating to the remaining sections
- If no sections remain (we check for "status = AVAILABLE" instead), ALL review question assignments are deleted

Also here:
- Added a generated column to "review_question_assignment" to show the template section code
- Update migration script (with the above plus a couple of refinements to existing)
- Update documentation regarding data/schema migration

2022-02-27 20:18 UTC, nmadruga commented
> * If no sections remain (we check for "status = AVAILABLE" instead), ALL review question assignments are deleted

I was thinking about this one... This will change slightly the logic that we added previously. Basically we wanted to keep the state of a previous review done by a reviewer when they get un-assigned from a review. Just in case it is re-assigned to them again iit would be keeping their previous reviewResponses.

I was lookiing for where this was explained in the Wiki, but could only find this:

> [Re-Assignment](https://github.com/openmsupply/application-manager-web-app/wiki/Assignment-Process#re-assignment)
> A GraphQL mutation reassignReviewAssignment runs on the front-end when one assigner:
> 
> selects re-assign in the drop down
> selects the new reviewer in drop down for a section (or all sections).
> review_assignment.trigger for previous assignment is set to ON_REVIEW_UNASSIGN.
> review_assignment.trigger for new assignment is set to ON_REVIEW_REASSIGN.
> Changes status of previous review_assignment to Available and flag is_locked to True.
> Changes status of new review_assignment to Assigned.
> Sets assignerId of current user in the new assignment.
> Adds review_question_assignment (for each question on the section assigned) to review_assignment.
> Other updates done on the server-side:
> If an existing review was connected to previous assignment will change the review.status from Draft to Discontinued.
> **If an existing review was connected to new assignment will change the review.status from Discontinued to Draft.**

2022-02-27 20:49 UTC, nmadruga reviewed
Looks good. I also tested using the snapshot `__just_before_assignment`, and saw the questions being correctly removed from one assignment and created on the new assignment to another user. And I was thinking about the idea of `DISCUTINUED` status. It seems it's going to be very hard to keep both logic. IIf we want to do half re-assignment I don't think we can also keep the ability of **continuing** a previously assigned (and unassigned) review questions. So I'm happy with just changing the docs on the front end so we remove the logic for DISCONTINUE a review.

2022-02-28 23:49 UTC, CarlosNZ commented
Okay, have added significant changes to update some of the functions to handle the removal of review_question_assignments and add migration code. Can be tested with https://github.com/openmsupply/application-manager-web-app/pull/1128

2022-03-02 22:44 UTC, nmadruga requested changes
Some hardcoded ids, I'm confused with what needs to be included and what is temp code that you were using to test with this particular example

2022-03-02 22:44 UTC, nmadruga commented on database/buildSchema/34_review_status_history.sql
> +                    id = 236))
Something left behind here?

2022-03-02 22:44 UTC, nmadruga commented on database/migration/migrateData.ts
> +          WHERE id = 236))
Again something that might be left behind?

2022-03-02 22:44 UTC, nmadruga commented on plugins/action_update_review_status/src/databaseMethods.ts
> +    WHERE ra.id = 28
Another hardcoded id

2022-03-02 22:50 UTC, CarlosNZ commented
> Some hardcoded ids, I'm confused with what needs to be included and what is temp code that you were using to test with this particular example

Ooops, sorry. 😳

Fixed now dcdba919

2022-03-03 04:11 UTC, nmadruga approved these changes

2022-03-03 21:39 UTC, merged